### PR TITLE
Fix nfs location

### PR DESCRIPTION
**Pull request by hamishivi**
Fixes NFS location bug introduced in #54

Changes proposed in this pull request:

- Replace `/net/nfs` with `/net/nfs.cirrascale`. The former doesn't actually work for nfs, tested [here](https://beaker.org/ex/01GS634EY28A8P6D7R8P5S0Q34/tasks/01GS634EZES1BX8NJ8DND82Y19/job/01GS634S4SF24HC108KK6J2RDY). I have tested that using `/net/nfs.cirrascale` instead works [here](https://beaker.org/ex/01GS64801CBXAK5FVVGHYVCF4R/tasks/01GS648031C6DHVNGAC8XH4CG0/job/01GS6482J7KGAW40GG21G45SVS).

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/beaker-py/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/allenai/beaker-py/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

### CODE REVIEW

**Comment by epwalsh** [comment]
Huh, this *should* work. Running `ls /net/nfs/allennlp/hamishi/.hf/` directly on `allennlp-cirrascale-01` works fine. @codeviking any idea what's wrong here?

**Review by epwalsh — APPROVED** [review]
Oh well! I just pushed one change to ensure we only default to this on cirrascale clusters.

**Comment by codeviking** [comment]
No idea. Do we know what host this failed on? It's possible the generic NFS paths are missing on that machine, because of some sort of configuration error.

**Comment by epwalsh** [comment]
It was on `allennlp-cirrascale-01.reviz.ai2.in`, which definitely has the generic NFS path

**Comment by codeviking** [comment]
Right, as you noted, it seems to work:

```
sams@allennlp-cirrascale-01:~$ ls /net/nfs/allennlp/hamishi/.hf
datasets  hub  modules  transformers
```

Maybe there was a network hiccup (though NFS is supposed to absorb those). Is it possible the `.hf` directory didn't exist yet, and something else created it?

**Pull request merged**
